# -*- coding: utf-8 -*-
"""Data_Test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gibmi2zGsUxqhWBwx1v3kYWOi5xJvDjO
"""

# from google.colab import drive
# drive.mount('/content/drive')

# my_file = '/content/drive/MyDrive/Internship_Data_Test/Busy Buffet Dataset.xlsx'
my_file = 'Busy Buffet Dataset.xlsx'

import pandas as pd

import matplotlib.pyplot as plt

data = pd.read_excel(my_file, sheet_name=None, dtype=str)

day_data = []

for sheet_name, df in data.items():

    if sheet_name == '133':
        df['day'] = 'day1'
    elif sheet_name == '143':
        df['day'] = 'day2'
    elif sheet_name == '153':
        df['day'] = 'day3'
    elif sheet_name == '173':
        df['day'] = 'day4'
    else:
        df['day'] = 'day5'

    day_data.append(df)

all_df = pd.concat(day_data, ignore_index=True)

all_df['queue_start'] = all_df['queue_start'].fillna(0)
all_df['queue_end'] = all_df['queue_end'].fillna(0)

all_df = all_df.drop(columns=['Unnamed: 8', 'Unnamed: 9'], errors='ignore')

display(all_df)

all_df.info()
display(all_df.head())

all_df['queue_start'] = pd.to_timedelta(all_df['queue_start'].astype(str), errors='coerce')
all_df['queue_end'] = pd.to_timedelta(all_df['queue_end'].astype(str), errors='coerce')

all_df['queue_time'] = (all_df['queue_end'] - all_df['queue_start']).dt.total_seconds() / 60

all_df = all_df.dropna(subset=['pax'])

print(all_df.isna().sum())

# 1. สร้างคอลัมน์ใหม่เพื่อแยกกลุ่ม
all_df['status'] = 'ได้ที่นั่งทันที'
all_df.loc[all_df['table_no.'].isna(), 'status'] = 'รอแล้วจาก'

# 2. โค้ดเช็คค่าว่างในคอลัมน์ (เพื่อดูว่าแยกกลุ่มสำเร็จไหม)
# ถ้าแยกถูก แถวที่เป็น 'Abandoned' จะต้องมีค่าว่างในคอลัมน์ 'table_no.' ครบทั้ง 14 ราย
print("--- เช็คค่าว่างแยกตามสถานะ ---")
print(all_df.groupby('status')[['table_no.', 'meal_start']].apply(lambda x: x.isna().sum()))

all_df['meal_start'] = pd.to_timedelta(all_df['meal_start'].astype(str), errors='coerce')
all_df['meal_end'] = pd.to_timedelta(all_df['meal_end'].astype(str), errors='coerce')

all_df['meal_time'] = (all_df['meal_end'] - all_df['meal_start']).dt.total_seconds() / 60

#Task1
queue_mean = all_df['queue_time'].mean().round(4)
queue_midian = all_df['queue_time'].median()

print("queue_mean:",queue_mean)
print("queue_midian:",queue_midian)

#filter queue
wait_df = all_df[all_df['queue_time'] > 0]   # คนที่รอ
no_wait_df = all_df[all_df['queue_time'] == 0]  # คนที่ไม่รอ

mean_wait = wait_df['queue_time'].mean()
median_wait = wait_df['queue_time'].median()

print(f"Mean (เฉพาะคนที่รอ): {mean_wait:.2f}")
print(f"Median (เฉพาะคนที่รอ): {median_wait:.2f}")
pct_no_wait = (all_df['queue_time'] == 0).mean() * 100
print(f"% คนที่ไม่ต้องรอ: {pct_no_wait:.2f}%")

# จำนวนคนทั้งหมด
total = len(all_df)

# คนที่รอนานกว่า 30 นาที
long_wait = all_df[all_df['queue_time'] > 30]

# คิดเป็น %
percent_long_wait = (len(long_wait) / total) * 100

print(f"% คนที่รอนาน (>30 นาที): {percent_long_wait:.2f}%")

#% ที่ทนไม่ไหวแล้วเดินออก
waited = all_df[all_df['queue_time'] > 0]

# walk-away จาก status
walk_away = waited[waited['status'] == 'รอแล้วจาก']

percent_walk_away = (len(walk_away) / len(waited)) * 100

print(f"% Walk-away (เฉพาะคนที่รอ): {percent_walk_away:.2f}%")

# จำนวน walk-away
walk_away = all_df[all_df['status'] == 'รอแล้วจาก']

# %
percent_walk_away = (len(walk_away) / total) * 100

print(f"% Walk-away: {percent_walk_away:.2f}%")

# เอาเฉพาะคนที่รอ
waited = all_df[all_df['queue_time'] > 0]

# คำนวณ walk-away แยกกลุ่ม
walkaway_by_type = waited.groupby('Guest_type')['status'].apply(
    lambda x: (x == 'รอแล้วจาก').mean() * 100
)

print(walkaway_by_type)

"""# **เริ่มใหม่**"""

df = all_df.rename(columns={
    'Unnamed: 8': 'queue_time',
    'Unnamed: 9': 'meal_time'
})
df['queue_time'] = pd.to_timedelta(df['queue_time'], errors='coerce')
df['meal_time'] = pd.to_timedelta(df['meal_time'], errors='coerce')

"""1. สำหรับกลุ่ม In-house (แขกโรงแรม):

อัตราส่วนการรอคิว: คำนวณว่ามีลูกค้า Guest_type แบบ 'In house' กี่เปอร์เซ็นต์ที่ต้องรอคิว (มีข้อมูลใน queue_start) เทียบกับคนที่ได้โต๊ะเลยโดยไม่ต้องรอ  
"""

#เปลี่ยนไทป
all_df['queue_start'] = pd.to_timedelta(all_df['queue_start'], errors='coerce')
#เลือกเฉพาะ inhouse
df_inhouse = all_df[all_df['Guest_type'] == 'In house']

waiting = (df_inhouse['queue_start'] > pd.Timedelta(0)).sum()
no_wait = (df_inhouse['queue_start'] == pd.Timedelta(0)).sum()

# จำนวนทั้งหมด
total = len(df_inhouse)

print("เฉพาะลูกค้าIn house")
print(f"ต้องรอคิว: {(waiting/total)*100:.2f}%")
print(f"ไม่ต้องรอคิว: {(no_wait/total)*100:.2f}%")

"""คำนวณหาค่าเฉลี่ย (Mean) และค่ามัธยฐาน (Median) ของคอลัมน์ queue_time สำหรับกลุ่ม 'In house' เพื่อดูว่าพวกเขารอโต๊ะนานแค่ไหน"""

# เลือกเฉพาะลูกค้า In house
df_inhouse = all_df[all_df['Guest_type'] == 'In house']

# คำนวณค่าเฉลี่ย (Mean)
mean_queue = df_inhouse['queue_time'].mean().round(2)

# คำนวณค่ามัธยฐาน (Median)
median_queue = df_inhouse['queue_time'].median()

print("Mean queue time (In house):", mean_queue)
print("Median queue time (In house):", median_queue)

"""2. สำหรับกลุ่ม Walk-in (ลูกค้าภายนอก):

ระยะเวลารอคิว: คำนวณค่าเฉลี่ย (Mean) และค่ามัธยฐาน (Median) ของ queue_time สำหรับกลุ่ม 'Walk in' เพื่อพิสูจน์ว่าพวกเขารอ "นานมาก" จริงหรือไม่
"""

# เลือกเฉพาะลูกค้า Walk in
df_inhouse = all_df[all_df['Guest_type'] == 'Walk in']

# คำนวณค่าเฉลี่ย (Mean)
mean_queue = df_inhouse['queue_time'].mean().round(2)

# คำนวณค่ามัธยฐาน (Median)
median_queue = df_inhouse['queue_time'].median()

print("Mean queue time (Walk in):", mean_queue)
print("Median queue time (Walk in):", median_queue)

"""อัตราการทิ้งคิว (Walk-away Rate): คำนวณจำนวน**ลูกค้า 'Walk in' ที่มีสถานะเดินหนี** (ตาม Data Logic คือมีข้อมูลในคิวแต่คอลัมน์ meal_start เป็นว่าง/NaN หรือในตารางของน้ำว้าคือ status == 'รอแล้วจาก') เทียบกับจำนวน Walk-in ทั้งหมด"""

# เลือกเฉพาะ Walk-in
df_walkin = all_df[all_df['Guest_type'] == 'Walk in']

# จำนวนทั้งหมด
total_walkin = len(df_walkin)

# จำนวนที่ walk-away (สถานะ = 'รอแล้วจาก')
walkaway = (df_walkin['status'] == 'รอแล้วจาก').sum()

# คำนวณ %
walkaway_pct = (walkaway / total_walkin) * 100

print("Walk-in total:", total_walkin)
print("Walk-away:", walkaway)
print(f"Walk-away %: {walkaway_pct:.2f}%")

"""จุดตัดความอดทน (Drop-off Point): หาค่าเฉลี่ยของ queue_time เฉพาะกลุ่มที่เดินหนี (Walk-away) เพื่อดูว่าโดยเฉลี่ยแล้วลูกค้ารอนานกี่นาทีถึงตัดสินใจทิ้งคิว"""

df_walkaway = all_df[all_df['status'] == 'รอแล้วจาก']

mean_wait = df_walkaway['queue_time'].mean()

print(f"Average queue time: {mean_wait:.2f}")

# ใช้ .replace() เปลี่ยนชื่อข้อมูลในคอลัมน์ status
all_df['status'] = all_df['status'].replace({
    'ได้ที่นั่งทันที': 'Seated',
    'รอแล้วจาก': 'Walk-away',
})

# ลองเช็กดูว่าชื่อเปลี่ยนหรือยัง
print(df['status'].value_counts())

# ---------------------------------------------------------
# กราฟที่ 1: ระยะเวลารอคิวเฉลี่ย (เทียบ In-house กับ Walk-in)
# ---------------------------------------------------------
# หาค่าเฉลี่ย
avg_wait = all_df.groupby('Guest_type')['queue_time'].mean()

# พล็อตกราฟแท่ง
avg_wait.plot(kind='bar', color=['skyblue', 'salmon'], figsize=(6,4))
plt.title('Average Wait Time: In-house vs Walk-in')
plt.ylabel('Average Wait Time (Minutes)')
plt.xticks(rotation=0)
plt.show()

# ---------------------------------------------------------
# กราฟที่ 2: สถานะของลูกค้า Walk-in (ได้โต๊ะ vs ทิ้งคิว)
# ---------------------------------------------------------
# กรองเฉพาะ Walk in และนับจำนวนสถานะ
df_walkin = all_df[all_df['Guest_type'] == 'Walk in']
walkin_status_count = df_walkin['status'].value_counts()

# พล็อตกราฟแท่ง
walkin_status_count.plot(kind='bar', color=['lightgreen', 'orange', 'lightcoral'], figsize=(6,4))
plt.title('Walk-in Status: Seated vs Walk-away')
plt.ylabel('Number of Groups')
plt.xticks(rotation=0)
plt.show()

# ใช้ค่าที่คำนวณไว้แล้ว
sizes = [no_wait, waiting]
labels = ['Got table immediately', 'Waited']

plt.pie(sizes, labels=labels, autopct='%1.1f%%')
plt.title('In-house Customers Queue Status')
plt.axis('equal')

plt.show()

# 1. แปลงคอลัมน์ pax เป็นตัวเลขก่อนเลย (แก้ปัญหาตัวเลขต่อกันยาวเป็นหางว่าว)
df['pax'] = pd.to_numeric(df['pax'], errors='coerce')

# 2. จัดกลุ่มตามคอลัมน์ 'day' ที่น้ำว้าทำไว้แล้ว
# ทริค: คราวนี้เราไม่ใช้ .reset_index() เพื่อให้ 'day' กลายเป็น Index
# ซึ่งจะทำให้ Pandas พล็อตกราฟแท่งคู่ง่ายขึ้นมากค่ะ
daily_stats = df.groupby('day').agg(
    total_groups=('service_no.', 'count'),
    total_pax=('pax', 'sum')
)

print("ตารางสรุปจำนวนลูกค้าในแต่ละวัน:")
print(daily_stats)

daily_stats.plot(kind='bar', figsize=(8, 5), color=['#4C72B0', '#DD8452'], edgecolor='black')

# ตกแต่งกราฟ
plt.title('Daily Customer Volume\n(Is it really busy EVERY day)', fontsize=14)
plt.ylabel('Count')
plt.xlabel('Day')
plt.xticks(rotation=0) # ให้ชื่อวันในแนวนอนอ่านง่ายๆ
plt.legend(['Total Groups (Tables)', 'Total Pax (People)'])
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

df['meal_time'] = pd.to_numeric(all_df['meal_time'], errors='coerce')

# 2. กรองเอาเฉพาะลูกค้าที่ได้โต๊ะและมีเวลาทานอาหาร (ตัดค่าว่าง NaN ออก)
df_seated = all_df.dropna(subset=['meal_time']).copy()

# 3. หาค่าเฉลี่ยเปรียบเทียบ
mean_meal_time = df_seated.groupby('Guest_type')['meal_time'].mean().round(2)
print("ค่าเฉลี่ยเวลาทานอาหาร (นาที):")
print(mean_meal_time)

df_seated.boxplot(column='meal_time', by='Guest_type',
                  figsize=(8, 6), grid=True,
                  patch_artist=True,
                  boxprops=dict(facecolor='#ADD8E6', color='black'))

# ตกแต่งกราฟให้อ่านง่าย
plt.title('Meal Duration: In-house vs Walk-in\n(Do Walk-ins really sit all day?)', fontsize=14)
plt.suptitle('') # ลบ title อัตโนมัติที่ pandas สร้างมาซ้ำซ้อน
plt.ylabel('Meal Time (Minutes)', fontsize=12)
plt.xlabel('Guest Type', fontsize=12)

# ขีดเส้นแดงที่ 300 นาที (5 ชั่วโมง) ตามที่โปรโมชันโจทย์กำหนดไว้
plt.axhline(y=300, color='red', linestyle='--', linewidth=1.5, label='5-Hour Promo Limit')
plt.legend()

plt.show()

